### ISSUE TITLE
ydn.error.ArgumentException: store name "NAME" not found

### ISSUE THREAD

**Issue by realkyton** [yathit/ydn-db#71]
YDN-DB tells me there was no store named 'tasks' when I try clearing it. It definately exists.

```
ydn.error.ArgumentException: store name "tasks" not found.
    at Error.C (http://localhost:3000/services/common/localStorage/ydndb.js:26:411)
    at ze.l.clear (http://localhost:3000/services/common/localStorage/ydndb.js:109:114)
    at T.l.clear (http://localhost:3000/services/common/localStorage/ydndb.js:182:193)
```

**Comment by yathit** [comment]
Please attach runnable code in jsbin or jsfiddle.

**Comment by realkyton** [comment]
Maybe I will tomorrow. clear() doesn't seem to work at all, at least for me:

```
ydn.error.ArgumentException: number of store names must more than 0
```

**Comment by yathit** [comment]
"Does not work for me" is the worst thing a programmer can say. Please improve your bug report skill.
